In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [3]:
df=pd.read_csv('train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
df.shape

(891, 12)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [32]:
obj= ['Sex','Cabin']

In [52]:
col_to_drop=['PassengerId','Name','Ticket','Embarked','Cabin']

In [51]:
clean_data=df

In [53]:
clean_data=df.drop(col_to_drop,axis=1)


In [54]:
clean_data.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0         0       3    male  22.0      1      0   7.2500
1         1       1  female  38.0      1      0  71.2833
2         1       3  female  26.0      0      0   7.9250
3         1       1  female  35.0      1      0  53.1000
4         0       3    male  35.0      0      0   8.0500

In [55]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
dtypes: float64(2), int64(4), object(1)
memory usage: 48.9+ KB


In [56]:
from sklearn.preprocessing import LabelEncoder

In [57]:
le=LabelEncoder()

In [58]:
clean_data['Sex']=le.fit_transform(clean_data['Sex'])

In [59]:
clean_data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0         0       3    1  22.0      1      0   7.2500
1         1       1    0  38.0      1      0  71.2833
2         1       3    0  26.0      0      0   7.9250
3         1       1    0  35.0      1      0  53.1000
4         0       3    1  35.0      0      0   8.0500

In [40]:
#df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [60]:
clean_data=clean_data.fillna(clean_data['Age'].mean())

In [62]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int32  
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
dtypes: float64(2), int32(1), int64(4)
memory usage: 45.4 KB


In [63]:
X=clean_data.drop('Survived',axis=1)

In [64]:
X.head()

Pclass  Sex   Age  SibSp  Parch     Fare
0       3    1  22.0      1      0   7.2500
1       1    0  38.0      1      0  71.2833
2       3    0  26.0      0      0   7.9250
3       1    0  35.0      1      0  53.1000
4       3    1  35.0      0      0   8.0500

In [65]:
y=clean_data['Survived']

In [66]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [67]:
X.shape,y.shape

((891, 6), (891,))

In [68]:
from sklearn.model_selection import train_test_split

In [115]:
X_train,X_test,y_train,y_test= train_test_split(X,y, test_size=0.1,random_state=4)

In [116]:
from sklearn.tree import DecisionTreeClassifier

In [117]:
clf=DecisionTreeClassifier(criterion='gini' ,max_depth=3)

In [118]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=3)

In [119]:
clf.score(X_test,y_test)

0.8555555555555555

In [121]:
y_pred=clf.predict(X_test)

In [123]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[58,  5],
       [ 8, 19]], dtype=int64)

In [124]:
# Accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)


0.8555555555555555

In [127]:
# Recall
from sklearn.metrics import recall_score
recall_score(y_test, y_pred, average=None)


array([0.92063492, 0.7037037 ])

In [128]:
# Precision
from sklearn.metrics import precision_score
precision_score(y_test, y_pred, average=None)

array([0.87878788, 0.79166667])

# kaggle submission


In [133]:
test_df= pd.read_csv('clean_data.csv')


In [148]:
ps=pd.read_csv('clean_data.csv')

In [149]:
ps.head()

Unnamed: 0  PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare
0           0          892       3    1  34.5      0      0   7.8292
1           1          893       3    0  47.0      1      0   7.0000
2           2          894       2    1  62.0      0      0   9.6875
3           3          895       3    1  27.0      0      0   8.6625
4           4          896       3    0  22.0      1      1  12.2875

In [134]:
test_df.head()

Unnamed: 0  PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare
0           0          892       3    1  34.5      0      0   7.8292
1           1          893       3    0  47.0      1      0   7.0000
2           2          894       2    1  62.0      0      0   9.6875
3           3          895       3    1  27.0      0      0   8.6625
4           4          896       3    0  22.0      1      1  12.2875

In [136]:
test_df.drop('Unnamed: 0',axis=1,inplace=True)

In [139]:
test_df = test_df[[	'Pclass','Sex','Age','SibSp','Parch','Fare']]

In [140]:
test_df.head()

Pclass  Sex   Age  SibSp  Parch     Fare
0       3    1  34.5      0      0   7.8292
1       3    0  47.0      1      0   7.0000
2       2    1  62.0      0      0   9.6875
3       3    1  27.0      0      0   8.6625
4       3    0  22.0      1      1  12.2875

# prediction

In [141]:
predictions= clf.predict(test_df)

In [144]:
predictions

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [158]:
submission_df = pd.DataFrame({'PassengerId' : ps["PassengerId"],'Survived' : predictions})

In [159]:
submission_df.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [160]:
submission = submission_df.to_csv('submission.csv',index=False)